### PR TITLE
use fix-ev

### PR DESCRIPTION
**Pull request by juliangruber**
as in #4

### CODE REVIEW

**Comment by defunctzombie** [comment]
Squash commits (when review is done). Commit message needs more love.

Tests need more love.

**Comment by juliangruber** [comment]
fix-ev has tests already

**Comment by defunctzombie** [comment]
Even if fix-ev has tests, this module's use of it and expected behavior also need tests.

**Comment by juliangruber** [comment]
you can just copy over fix-ev's tests if you want them

**Comment by defunctzombie** [comment]
Part of a nice PR is tests :)

**Comment by juliangruber** [comment]
i'm not concerned with nice PRs ;)

**Pull request closed without merging**
